# generated by datamodel-codegen:
#   filename:  copilot-mcp.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict


class Type(StrEnum):
    stdio = "stdio"
    sse = "sse"
    http = "http"


class CopilotMcpServer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    command: str | None = None
    args: list[str] | None = None
    url: str | None = None
    inputs: list[dict[str, Any]] | None = None
    env: dict[str, str] | None = None


class CopilotMcpConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    servers: dict[str, CopilotMcpServer] | None = None
