# generated by datamodel-codegen:
#   filename:  opencode-mcp.schema.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, conint


class Mcp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool


class Skills(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    paths: list[str] | None = Field(
        None, description="Additional paths to skill folders"
    )
    urls: list[str] | None = Field(
        None,
        description="URLs to fetch skills from (e.g., https://example.com/.well-known/skills/)",
    )


class Type(StrEnum):
    local = "local"


class McpLocalConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type = Field(..., description="Type of MCP server connection")
    command: list[str] = Field(
        ..., description="Command and arguments to run the MCP server"
    )
    cwd: str | None = Field(
        None,
        description="Working directory for the MCP server process. Relative paths resolve from the workspace directory.",
    )
    environment: dict[str, str] | None = Field(
        None, description="Environment variables to set when running the MCP server"
    )
    enabled: bool | None = Field(
        None, description="Enable or disable the MCP server on startup"
    )
    timeout: conint(le=9007199254740991, gt=0) | None = Field(
        None,
        description="Timeout in ms for MCP server requests. Defaults to 5000 (5 seconds) if not specified.",
    )


class McpOAuthConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    clientId: str | None = Field(
        None,
        description="OAuth client ID. If not provided, dynamic client registration (RFC 7591) will be attempted.",
    )
    clientSecret: str | None = Field(
        None,
        description="OAuth client secret (if required by the authorization server)",
    )
    scope: str | None = Field(
        None, description="OAuth scopes to request during authorization"
    )
    callbackPort: conint(ge=1, le=65535) | None = Field(
        None,
        description="Port for the local OAuth callback server (default: 19876). Shorthand for redirectUri when only the port needs changing. Ignored if redirectUri is set.",
    )
    redirectUri: str | None = Field(
        None,
        description="OAuth redirect URI (default: http://127.0.0.1:19876/mcp/oauth/callback).",
    )


class Type1(StrEnum):
    remote = "remote"


class Oauth(Enum):
    boolean_False = False


class McpRemoteConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type1 = Field(..., description="Type of MCP server connection")
    url: str = Field(..., description="URL of the remote MCP server")
    enabled: bool | None = Field(
        None, description="Enable or disable the MCP server on startup"
    )
    headers: dict[str, str] | None = Field(
        None, description="Headers to send with the request"
    )
    oauth: McpOAuthConfig | Oauth | None = Field(
        None,
        description="OAuth authentication configuration for the MCP server. Set to false to disable OAuth auto-detection.",
    )
    timeout: conint(le=9007199254740991, gt=0) | None = Field(
        None,
        description="Timeout in ms for MCP server requests. Defaults to 5000 (5 seconds) if not specified.",
    )


class OpenCodeMcpConfig(BaseModel):
    mcp: dict[str, McpLocalConfig | McpRemoteConfig | Mcp] | None = Field(
        None, description="MCP (Model Context Protocol) server configurations"
    )
    plugin: list[str | tuple[str, dict[str, Any]]] | None = None
    skills: Skills | None = Field(None, description="Additional skill folder paths")
