# generated by datamodel-codegen:
#   filename:  pi-mcp.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Settings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    toolPrefix: str | None = None
    idleTimeout: int | None = None


class PiMcpServer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    command: str | None = None
    args: list[str] | None = None
    url: str | None = None
    lifecycle: str | None = None
    idleTimeout: int | None = None
    directTools: list[str] | None = None
    debug: bool | None = None
    env: dict[str, str] | None = None


class PiMcpConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    settings: Settings | None = None
    mcpServers: dict[str, PiMcpServer] | None = None
