# generated by datamodel-codegen:
#   filename:  pi-mcp.schema.json
#
# HAND-PATCHED 2026-08-31: added OAuthConfig and PiMcpServer.auth/oauth.
# pi-mcp.schema.json is not vendored in this repo (per spec D6, Pi has no
# published schema to codegen from — this file was hand-authored from
# whatever was known about Pi's MCP config at the time), so there is no
# schema source to regenerate from. These two fields were instead verified
# directly against pi.dev/packages/pi-mcp-adapter's live docs (fetched
# 2026-08-31). If a real pi-mcp.schema.json is ever vendored, reconcile
# against it rather than trusting this by-hand addition indefinitely.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Settings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    toolPrefix: str | None = None
    idleTimeout: int | None = None


class OAuthConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    clientId: str | None = None
    clientSecret: str | None = None
    scope: str | None = None
    redirectUri: str | None = None
    authServerMetadataUrl: str | None = None


class PiMcpServer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    command: str | None = None
    args: list[str] | None = None
    url: str | None = None
    lifecycle: str | None = None
    idleTimeout: int | None = None
    directTools: list[str] | None = None
    debug: bool | None = None
    env: dict[str, str] | None = None
    auth: str | None = None
    oauth: OAuthConfig | None = None


class PiMcpConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    settings: Settings | None = None
    mcpServers: dict[str, PiMcpServer] | None = None
