from __future__ import annotations

from .diff import Drift, diff
from .jsonio import load_json_object, write_json
from .manifest import Manifest, ManifestError, ManifestOptions, load_manifest
from .models import (
    AgentPlatform,
    ApprovalMode,
    ApprovalPolicy,
    CapabilityScope,
    DeclarativeHook,
    FrontmatterRule,
    Hook,
    HookEvent,
    InstructionsConfig,
    LspServer,
    McpServer,
    MergeStrategy,
    PluginRegistration,
    RemoteServer,
    Scope,
    ScopeTarget,
    SearchStrategy,
    SkillSource,
    StdioServer,
)
from .plan import InstallResult, RegistrationBundle, apply, apply_all
from .prune import (
    PlatformState,
    apply_with_prune,
    default_state_path,
    hook_identity,
    load_state,
    write_state,
)
from .registry import detect_installed_platforms, get_platform, known_platforms

__all__ = [
    "AgentPlatform",
    "ApprovalMode",
    "ApprovalPolicy",
    "CapabilityScope",
    "DeclarativeHook",
    "Drift",
    "FrontmatterRule",
    "Hook",
    "HookEvent",
    "InstallResult",
    "InstructionsConfig",
    "LspServer",
    "Manifest",
    "ManifestError",
    "ManifestOptions",
    "McpServer",
    "MergeStrategy",
    "PlatformState",
    "PluginRegistration",
    "RegistrationBundle",
    "RemoteServer",
    "Scope",
    "ScopeTarget",
    "SearchStrategy",
    "SkillSource",
    "StdioServer",
    "apply",
    "apply_all",
    "apply_with_prune",
    "default_state_path",
    "detect_installed_platforms",
    "diff",
    "get_platform",
    "hook_identity",
    "known_platforms",
    "load_json_object",
    "load_manifest",
    "load_state",
    "write_json",
    "write_state",
]
