from __future__ import annotations

from .jsonio import load_json_object, write_json
from .manifest import Manifest, ManifestError, ManifestOptions, load_manifest
from .models import (
    AgentPlatform,
    ApprovalMode,
    ApprovalPolicy,
    CapabilityScope,
    DeclarativeHook,
    FrontmatterRule,
    Hook,
    HookEvent,
    InstructionsConfig,
    LspServer,
    McpServer,
    MergeStrategy,
    PluginRegistration,
    RemoteServer,
    Scope,
    ScopeTarget,
    SearchStrategy,
    SkillSource,
    StdioServer,
)
from .plan import InstallResult, RegistrationBundle, apply, apply_all
from .registry import detect_installed_platforms, get_platform, known_platforms

__all__ = [
    "AgentPlatform",
    "ApprovalMode",
    "ApprovalPolicy",
    "CapabilityScope",
    "DeclarativeHook",
    "FrontmatterRule",
    "Hook",
    "HookEvent",
    "InstallResult",
    "InstructionsConfig",
    "LspServer",
    "Manifest",
    "ManifestError",
    "ManifestOptions",
    "McpServer",
    "MergeStrategy",
    "PluginRegistration",
    "RegistrationBundle",
    "RemoteServer",
    "Scope",
    "ScopeTarget",
    "SearchStrategy",
    "SkillSource",
    "StdioServer",
    "apply",
    "apply_all",
    "detect_installed_platforms",
    "get_platform",
    "known_platforms",
    "load_json_object",
    "load_manifest",
    "write_json",
]
