"""Tests for the cross-repo bridge: confidence scoring and integration.

Unit tests for the confidence scoring function cover each heuristic independently
and in combination.  Integration tests (requiring omnigraph + tree-sitter) verify
full indexing and store round-trips.
"""

import pytest

from witan_code.bridge_extractors import (
    _compute_file_confidence,
    adjust_confidence,
    extract_file_bindings,
)

from .conftest import requires_stack


# ── Confidence scoring unit tests ─────────────────────────────────
# All tests operate on _compute_file_confidence directly; no omnigraph needed.


def test_load_test_path_penalizes_score():
    """load_test_path penalty: file under a load_testing/ directory."""
    score = _compute_file_confidence(
        "load_testing/backend/client/v0/api.ts", "", "/api/v0/courses/"
    )
    assert score < 0.5, f"load_test_path should penalize; got {score}"


def test_k6_path_segment_penalizes_score():
    """load_test_path penalty applies to /k6/ path segments."""
    score = _compute_file_confidence("perf/k6/scenarios.ts", "", "/api/v0/courses/")
    assert score < 0.5, f"k6 path segment should penalize; got {score}"


def test_load_test_framework_import_penalizes():
    """load_test_framework penalty: file imports k6."""
    content = "import http from 'k6/http';\nimport { sleep } from 'k6';\n"
    score = _compute_file_confidence("client.ts", content, "/api/v0/courses/")
    assert score < 0.5, f"k6 framework import should penalize; got {score}"


def test_load_test_framework_locust_penalizes():
    """load_test_framework penalty applies to locust imports."""
    content = "from 'locust' import HttpUser\n"
    score = _compute_file_confidence("test_load.ts", content, "/api/v0/things/")
    assert score < 0.5, f"locust import should penalize; got {score}"


def test_load_test_framework_artillery_penalizes():
    """load_test_framework penalty applies to artillery imports."""
    content = "import stuff from 'artillery';\n"
    score = _compute_file_confidence("perf.ts", content, "/api/v0/things/")
    assert score < 0.5, f"artillery import should penalize; got {score}"


def test_relative_url_penalizes_score():
    """relative_url penalty: URL has no scheme."""
    score = _compute_file_confidence("src/client.ts", "", "/api/v0/profiles/")
    assert score < 0.5, f"relative URL should penalize; got {score}"


def test_generated_file_header_heavily_penalizes():
    """generated_file penalty: file with DO NOT EDIT header."""
    content = "// DO NOT EDIT — generated by openapi-generator\nexport const x = 1;"
    score = _compute_file_confidence("src/generated.ts", content, "/api/v0/courses/")
    assert score < 0.1, f"generated file header should heavily penalize; got {score}"


def test_generated_file_at_generated_penalizes():
    """generated_file penalty: file with @generated annotation."""
    content = "/* @generated */\nexport const x = 1;"
    score = _compute_file_confidence("src/gen.ts", content, "/api/v0/courses/")
    assert score < 0.1, f"@generated file should heavily penalize; got {score}"


def test_same_origin_helper_penalizes():
    """same_origin_helper penalty: relative import to a csrf/fetch wrapper."""
    content = "import { fetchJSONWithCSRF } from '../utils/csrf';\n"
    score = _compute_file_confidence("src/actions.ts", content, "/api/v0/profiles/")
    assert score < 0.5, f"same-origin helper import should penalize; got {score}"


def test_same_origin_relative_api_client_penalizes():
    """same_origin_helper penalty: relative import to an api-client file."""
    content = "import { apiFetch } from './api-client';\n"
    score = _compute_file_confidence("src/actions.ts", content, "/api/v0/courses/")
    assert score < 0.5, f"relative api-client import should penalize; got {score}"


def test_explicit_hostname_boosts_score():
    """explicit_hostname boost: URL has scheme + host (absolute URL)."""
    score = _compute_file_confidence(
        "src/client.ts", "", "https://api.example.com/api/v0/courses/"
    )
    assert score > 0.5, f"explicit hostname should boost; got {score}"


def test_client_directory_boosts_score():
    """client_directory boost: file path contains /clients/."""
    score = _compute_file_confidence("src/clients/courses.ts", "", "/api/v0/courses/")
    assert score > 0.0, "client_directory should boost"
    # relative URL still penalizes but client_directory partially offsets
    baseline = _compute_file_confidence("src/other/courses.ts", "", "/api/v0/courses/")
    assert score > baseline, (
        f"client dir path ({score}) should score higher than non-client ({baseline})"
    )


def test_client_and_hostname_both_boost():
    """client_directory + explicit_hostname compound boost > 0.7."""
    score = _compute_file_confidence(
        "src/clients/courses.ts",
        "",
        "https://api.example.com/api/v0/courses/",
    )
    assert score > 0.7, f"client dir + hostname should push score > 0.7; got {score}"


def test_score_clamped_to_zero():
    """Multiple penalties cannot push score below 0.0."""
    content = "// DO NOT EDIT — generated\nimport http from 'k6/http';\n"
    score = _compute_file_confidence("load_testing/k6/api.ts", content, "/api/v0/x/")
    assert score == 0.0, f"overlapping penalties should clamp at 0.0; got {score}"


def test_score_clamped_to_one():
    """Score cannot exceed 1.0 even with all boosts stacking."""
    score = _compute_file_confidence(
        "src/clients/integrations/service.ts",
        "",
        "https://api.example.com/api/v0/courses/",
    )
    assert score <= 1.0, f"score must not exceed 1.0; got {score}"


# ── Store-level adjust_confidence tests ───────────────────────────


def _ep_consumer(key_norm="k", file="src/x.ts", confidence=0.5):
    from witan_code.bridge_extractors import ParsedBinding

    return ParsedBinding(
        kind="endpoint",
        key=key_norm,
        key_norm=key_norm,
        role="consumer",
        file=file,
        confidence=confidence,
    )


def test_self_provided_key_penalizes():
    """self_provided_key: consumer repo also provides same key_norm."""
    b = _ep_consumer(key_norm="/api/v0/profiles/{}", confidence=0.5)
    provider_keys = frozenset(
        [("https://github.com/test/repo-a", "/api/v0/profiles/{}")]
    )
    adjust_confidence(
        b,
        consumer_repo="https://github.com/test/repo-a",
        provider_keys=provider_keys,
    )
    assert b.confidence < 0.5, f"self_provided_key should penalize; got {b.confidence}"


def test_known_provider_package_boosts():
    """known_provider_package: file imports a package known to be provided by another repo."""
    b = _ep_consumer(confidence=0.5)
    adjust_confidence(
        b,
        consumer_repo="https://github.com/test/repo-a",
        provider_keys=frozenset(),
        has_known_provider_package=True,
    )
    assert b.confidence > 0.5, (
        f"known_provider_package should boost; got {b.confidence}"
    )


def test_adjust_confidence_skips_non_endpoint():
    """adjust_confidence does not modify non-endpoint bindings."""
    from witan_code.bridge_extractors import ParsedBinding

    b = ParsedBinding(
        kind="env_var",
        key="FOO",
        key_norm="FOO",
        role="consumer",
        file="x.py",
        confidence=0.9,
    )
    original = b.confidence
    adjust_confidence(
        b,
        consumer_repo="repo",
        provider_keys=frozenset([("repo", "FOO")]),
    )
    assert b.confidence == original, "non-endpoint bindings must not be adjusted"


def test_adjust_confidence_skips_provider():
    """adjust_confidence does not modify provider bindings."""
    from witan_code.bridge_extractors import ParsedBinding

    b = ParsedBinding(
        kind="endpoint",
        key="/api/v0/x/",
        key_norm="/api/v0/x/",
        role="provider",
        file="openapi.yaml",
        confidence=1.0,
    )
    adjust_confidence(
        b,
        consumer_repo="repo",
        provider_keys=frozenset([("repo", "/api/v0/x/")]),
    )
    assert b.confidence == 1.0, "provider bindings must not be adjusted"


# ── extract_file_bindings integration ─────────────────────────────


NORMAL_TS_CLIENT = """\
export async function listCourses(id) {
  const path = `/api/v1/courses/${id}/`;
  const base = process.env.NEXT_PUBLIC_MITX_ONLINE_BASE_URL;
  return fetch(base + path);
}
"""

K6_CLIENT = """\
import http from 'k6/http';
import { sleep } from 'k6';

export default function () {
  http.get('/api/v0/courses/');
  http.post('/api/v0/enrollments/');
  sleep(1);
}
"""

LOAD_TESTING_PATH = "load_testing/backend/client/v0/api.ts"

CSRF_CLIENT = """\
import { fetchJSONWithCSRF } from '../utils/csrf';
import { someUtil } from '@mitodl/some-package';

export function loadProfile(username) {
  const base = process.env.NEXT_PUBLIC_APP_BASE_URL;
  return fetchJSONWithCSRF('/api/v0/profiles/' + username + '/');
}
"""


def test_normal_ts_client_extracts_endpoint_with_confidence():
    """Normal TS client emits endpoint bindings; confidence defaults from heuristics."""
    bindings = extract_file_bindings(NORMAL_TS_CLIENT, "typescript", "src/client.ts")
    ep = [b for b in bindings if b.kind == "endpoint"]
    assert len(ep) >= 1, "normal TS client should emit endpoint consumers"
    for b in ep:
        assert 0.0 <= b.confidence <= 1.0, f"confidence out of range: {b.confidence}"


def test_k6_client_emits_low_confidence_endpoints():
    """k6 client emits endpoint bindings with confidence < 0.5 (no binary suppression)."""
    bindings = extract_file_bindings(K6_CLIENT, "typescript", "client.ts")
    ep = [b for b in bindings if b.kind == "endpoint"]
    assert ep, "k6 client should still emit endpoint binding records"
    for b in ep:
        assert b.confidence < 0.5, (
            f"k6 endpoint should have confidence < 0.5; got {b.confidence}"
        )


def test_load_testing_path_emits_low_confidence_endpoints():
    """Files under load_testing/ path emit endpoint bindings with confidence < 0.5."""
    bindings = extract_file_bindings(NORMAL_TS_CLIENT, "typescript", LOAD_TESTING_PATH)
    ep = [b for b in bindings if b.kind == "endpoint"]
    assert ep, "load_testing/ file should still emit endpoint binding records"
    for b in ep:
        assert b.confidence < 0.5, (
            f"load_testing/ endpoint should have confidence < 0.5; got {b.confidence}"
        )


def test_csrf_client_emits_low_confidence_endpoints():
    """CSRF-helper client emits endpoint bindings with low confidence (not suppressed)."""
    bindings = extract_file_bindings(CSRF_CLIENT, "typescript", "src/actions.ts")
    ep = [b for b in bindings if b.kind == "endpoint"]
    assert ep, "CSRF client should still emit endpoint binding records"
    for b in ep:
        assert b.confidence < 0.5, (
            f"csrf endpoint should have confidence < 0.5; got {b.confidence}"
        )


def test_csrf_client_still_extracts_package_and_env():
    """Package and env_var bindings in CSRF file are unaffected by confidence scoring."""
    bindings = extract_file_bindings(CSRF_CLIENT, "typescript", "src/actions.ts")
    pkg = [b for b in bindings if b.kind == "package"]
    env = [b for b in bindings if b.kind == "env_var"]
    assert any(b.key == "@mitodl/some-package" for b in pkg)
    assert any(b.key == "NEXT_PUBLIC_APP_BASE_URL" for b in env)
    # Non-endpoint consumers default to confidence=1.0
    for b in pkg + env:
        assert b.confidence == 1.0


# Repo A (mit-learn-like): a Django settings consumer + a NextJS endpoint/env
# consumer.
A_SETTINGS = """\
from main.envs import get_string

APP_BASE_URL = get_string("MITOL_APP_BASE_URL", None)
DEBUG = get_string("DEBUG", "false")
"""

A_CLIENT_TS = """\
export async function listCourses(id) {
  const path = `/api/v1/courses/${id}/`
  const base = process.env.NEXT_PUBLIC_MITX_ONLINE_BASE_URL
  return fetch(base + path)
}
"""

# Repo B (ol-infrastructure-like): a Pulumi stack config that sets the env var,
# plus an OpenAPI spec that serves the endpoint.
B_PULUMI = """\
config:
  learn_ai:env_vars:
    MITOL_APP_BASE_URL: "https://learn-ai-qa.ol.mit.edu"
    AI_DEFAULT_TUTOR_MODEL: "openai/gpt-4o"
"""

B_OPENAPI = (
    '{"openapi": "3.0.0", "paths": '
    '{"/api/v1/courses/{id}/": {"get": {"operationId": "courses_retrieve"}}}}'
)


def _fn(tool):
    return getattr(tool, "fn", tool)


def _index(srv, indexer, path):
    return _fn(srv.code_reindex)(path=str(path))


def _make_repos(tmp_path):
    a = tmp_path / "repo_a"
    (a / "main").mkdir(parents=True)
    (a / "main" / "settings.py").write_text(A_SETTINGS)
    (a / "client.ts").write_text(A_CLIENT_TS)

    b = tmp_path / "repo_b"
    b.mkdir()
    (b / "Pulumi.QA.yaml").write_text(B_PULUMI)
    (b / "openapi.json").write_text(B_OPENAPI)
    return a, b


@requires_stack
def test_cross_repo_env_and_endpoint_linkage(tmp_path, monkeypatch):
    from witan_code import config as cfg_mod
    from witan_code import indexer
    from witan_code import server as srv

    monkeypatch.setenv("WITAN_CODE_DIR", str(tmp_path / "code"))
    a, b = _make_repos(tmp_path)

    monkeypatch.setenv("WITAN_REPO", "https://github.com/test/repo-a")
    monkeypatch.setattr(srv, "cfg", cfg_mod.load())
    srv._clients.clear()
    stats_a = _index(srv, indexer, a)
    assert stats_a["bindings"] > 0

    monkeypatch.setenv("WITAN_REPO", "https://github.com/test/repo-b")
    monkeypatch.setattr(srv, "cfg", cfg_mod.load())
    srv._clients.clear()
    stats_b = _index(srv, indexer, b)
    assert stats_b["bindings"] > 0

    # env_var: repo-b (Pulumi) provides MITOL_APP_BASE_URL; repo-a (Django) consumes it.
    providers = _fn(srv.code_interface_providers)("env_var", "MITOL_APP_BASE_URL")
    assert {p["repo"] for p in providers} == {"https://github.com/test/repo-b"}

    consumers = _fn(srv.code_interface_consumers)("env_var", "MITOL_APP_BASE_URL")
    assert {c["repo"] for c in consumers} == {"https://github.com/test/repo-a"}

    # endpoint: openapi provider path joins the templated TS consumer path.
    ep_providers = _fn(srv.code_interface_providers)(
        "endpoint", "/api/v1/courses/{id}/"
    )
    assert any(p["repo"] == "https://github.com/test/repo-b" for p in ep_providers)
    ep_consumers = _fn(srv.code_interface_consumers)(
        "endpoint", "/api/v1/courses/{id}/"
    )
    assert any(c["repo"] == "https://github.com/test/repo-a" for c in ep_consumers)


C_PACKAGE_JSON = '{"name": "@mitodl/search-utils"}'

D_CLIENT_TS = """\
import { search } from '@mitodl/search-utils';

export function doSearch(q) {
  return fetch('/api/v0/search/' + q);
}
"""


@requires_stack
def test_known_provider_package_boost_sourced_from_stage1_symbol_table(
    tmp_path, monkeypatch
):
    """known_provider_package's cross-repo signal comes from another repo's
    Stage 1 RepoSymbol table (bridge.py provider_pkg_slugs), not a
    re-derivation from raw InterfaceBinding rows — verify the confidence
    boost actually lands end-to-end through a real index + bridge write.

    D_CLIENT_TS's endpoint consumer has only the relative_url penalty
    (-0.5, no other signal fires): base 0.5 - 0.5 = 0.0. The co-located
    package import of the repo-c-provided package should then boost it by
    +0.3 to 0.3.
    """
    from witan_code import config as cfg_mod
    from witan_code import indexer
    from witan_code import server as srv
    from witan_code.graph import OmnigraphClient

    monkeypatch.setenv("WITAN_CODE_DIR", str(tmp_path / "code"))

    c = tmp_path / "repo_c"
    c.mkdir()
    (c / "package.json").write_text(C_PACKAGE_JSON)
    d = tmp_path / "repo_d"
    d.mkdir()
    (d / "client.ts").write_text(D_CLIENT_TS)

    # Index the provider FIRST so its Stage 1 symbol table exists when
    # repo-d's write computes provider_pkg_slugs.
    monkeypatch.setenv("WITAN_REPO", "https://github.com/test/repo-c")
    monkeypatch.setattr(srv, "cfg", cfg_mod.load())
    srv._clients.clear()
    _index(srv, indexer, c)

    monkeypatch.setenv("WITAN_REPO", "https://github.com/test/repo-d")
    cfg = cfg_mod.load()
    monkeypatch.setattr(srv, "cfg", cfg)
    srv._clients.clear()
    _index(srv, indexer, d)

    client = OmnigraphClient(
        str(cfg_mod.bridge_store_path(cfg.code_dir)), cfg.queries_dir
    )
    rows = [
        r
        for r in client.read("bridge.gq", "all_bindings", {})
        if r["repo"] == "https://github.com/test/repo-d" and r["kind"] == "endpoint"
    ]
    assert len(rows) == 1
    assert rows[0]["confidence"] == pytest.approx(0.3)


@requires_stack
def test_cross_repo_impact_and_generic_flag(tmp_path, monkeypatch):
    from witan_code import config as cfg_mod
    from witan_code import indexer
    from witan_code import server as srv

    monkeypatch.setenv("WITAN_CODE_DIR", str(tmp_path / "code"))
    a, b = _make_repos(tmp_path)

    monkeypatch.setenv("WITAN_REPO", "https://github.com/test/repo-a")
    monkeypatch.setattr(srv, "cfg", cfg_mod.load())
    srv._clients.clear()
    _index(srv, indexer, a)

    monkeypatch.setenv("WITAN_REPO", "https://github.com/test/repo-b")
    monkeypatch.setattr(srv, "cfg", cfg_mod.load())
    srv._clients.clear()
    _index(srv, indexer, b)

    # Use the repo-a consumer binding's symbol_id to compute cross-repo impact.
    consumers = _fn(srv.code_interface_consumers)("env_var", "MITOL_APP_BASE_URL")
    symbol_id = consumers[0]["symbol_id"]
    assert symbol_id

    impact = _fn(srv.code_cross_repo_impact)(symbol_id)
    assert impact["symbol_id"] == symbol_id
    assert impact["bindings"], "the symbol's own bindings"
    # repo-b's provider of MITOL_APP_BASE_URL shows up cross-repo.
    assert any(
        b["repo"] == "https://github.com/test/repo-b" for b in impact["cross_repo"]
    )

    # DEBUG is generic → flagged and excluded from cross-repo fan-out.
    debug = _fn(srv.code_interface_consumers)("env_var", "DEBUG")
    assert all(d.get("generic") == "1" for d in debug)


@requires_stack
def test_incremental_reindex_keeps_sibling_bindings(tmp_path, monkeypatch):
    from witan_code import config as cfg_mod
    from witan_code import indexer
    from witan_code import server as srv

    monkeypatch.setenv("WITAN_CODE_DIR", str(tmp_path / "code"))
    monkeypatch.setenv("WITAN_REPO", "https://github.com/test/repo-a")
    a, _ = _make_repos(tmp_path)

    monkeypatch.setattr(srv, "cfg", cfg_mod.load())
    srv._clients.clear()
    _index(srv, indexer, a)  # full-repo index

    # Re-index ONLY the TS file (narrow target → per-file bridge purge).
    _index(srv, indexer, a / "client.ts")

    # The Python settings env-var binding (a sibling file) must survive.
    consumers = _fn(srv.code_interface_consumers)("env_var", "MITOL_APP_BASE_URL")
    assert {c["repo"] for c in consumers} == {"https://github.com/test/repo-a"}


@requires_stack
def test_bridge_tools_empty_without_store(tmp_path, monkeypatch):
    monkeypatch.setenv("WITAN_CODE_DIR", str(tmp_path / "empty"))
    monkeypatch.setenv("WITAN_REPO", "https://github.com/test/none")
    from witan_code import config as cfg_mod
    from witan_code import server as srv

    monkeypatch.setattr(srv, "cfg", cfg_mod.load())
    srv._clients.clear()
    assert _fn(srv.code_interface_providers)("env_var", "X") == []
    impact = _fn(srv.code_cross_repo_impact)("https://github.com/test/none#a.py::f")
    assert impact == {
        "symbol_id": "https://github.com/test/none#a.py::f",
        "bindings": [],
        "cross_repo": [],
    }


@requires_stack
def test_incremental_index_preserves_unchanged_file_bindings(tmp_path, monkeypatch):
    """A full-repo incremental index skips unchanged files; their bindings must
    survive the purge, and bindings for deleted files must be cleaned up."""
    from witan_code import config as cfg_mod
    from witan_code import indexer
    from witan_code.graph import OmnigraphClient

    monkeypatch.setenv("WITAN_REPO", "https://github.com/test/inc")
    monkeypatch.setenv("WITAN_CODE_DIR", str(tmp_path / "code"))
    cfg = cfg_mod.load()

    base = tmp_path / "repo"
    base.mkdir()
    (base / "a.ts").write_text('const a = fetch("/api/v0/aaa/");\n')
    (base / "b.ts").write_text('const b = fetch("/api/v0/bbb/");\n')
    indexer.index_path(base, config=cfg)

    def binding_files():
        client = OmnigraphClient(
            str(cfg_mod.bridge_store_path(cfg.code_dir)), cfg.queries_dir
        )
        return {
            r["file"]
            for r in client.read("bridge.gq", "all_bindings", {})
            if r["kind"] == "endpoint"
        }

    assert binding_files() == {"a.ts", "b.ts"}

    # Touch only a.ts; b.ts is skipped by the hash check but must keep its row.
    (base / "a.ts").write_text('const a = fetch("/api/v0/aaa2/");\n')
    stats = indexer.index_path(base, config=cfg)
    assert stats.skipped >= 1
    assert binding_files() == {"a.ts", "b.ts"}

    # Deleting b.ts must clear its bindings on the next full-repo index.
    (base / "b.ts").unlink()
    indexer.index_path(base, config=cfg)
    assert binding_files() == {"a.ts"}
